// SPDX-License-Identifier: AGPL-3.0-or-later

// Package proxyconfig embeds the same proxy examples shipped with the packages.
package proxyconfig

import (
	"embed"
	"errors"
	"flag"
	"fmt"
	"io"
	"net"
	"net/netip"
	"path/filepath"
	"strconv"
	"strings"
)

//go:embed caddy/Caddyfile nginx/witmoot.conf apache/witmoot.conf
var examples embed.FS

const app = "witmoot"
const exampleDomain = "board.example.org"
const defaultUpstream = "127.0.0.1:8082"
const proxyEnvironment = "WITMOOT_TRUSTED_PROXIES=127.0.0.1/32,::1/128"

type Options struct {
	Server, Domain, Upstream, Certificate, Key string
}

// Run prints a site configuration. It never opens the database, writes system
// files, obtains certificates, or reloads a running proxy.
func Run(args []string, out io.Writer) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: %s proxy-config caddy|nginx|apache --domain HOST [OPTIONS]", app)
	}
	if args[0] == "--help" || args[0] == "-h" {
		_, err := fmt.Fprintf(out, `Usage: %s proxy-config caddy|nginx|apache --domain HOST [OPTIONS]

Print a complete HTTPS site configuration to stdout. Caddy is recommended and
manages certificates automatically. nginx and Apache need existing certificates
and renewal; their default paths use /etc/letsencrypt/live/HOST/.
The upstream must be a loopback host:port on the same machine.

Example:
  %s proxy-config caddy --domain %s > %s.Caddyfile

Use "%s proxy-config nginx --help" for options. The generated comments include
the application settings to put in your service configuration.
`, app, app, exampleDomain, app, app)
		return err
	}
	options := Options{Server: args[0]}
	if _, err := templatePath(options.Server); err != nil {
		return err
	}
	flags := flag.NewFlagSet(app+" proxy-config "+options.Server, flag.ContinueOnError)
	flags.SetOutput(out)
	flags.StringVar(&options.Domain, "domain", "", "public hostname, without a scheme or path (required)")
	flags.StringVar(&options.Upstream, "upstream", defaultUpstream, "loopback application host:port; match the service's listen address")
	flags.StringVar(&options.Certificate, "tls-cert", "", "nginx/Apache certificate path (default: /etc/letsencrypt/live/HOST/fullchain.pem)")
	flags.StringVar(&options.Key, "tls-key", "", "nginx/Apache key path (default: /etc/letsencrypt/live/HOST/privkey.pem)")
	flags.Usage = func() {
		fmt.Fprintf(out, "Usage: %s proxy-config %s --domain HOST [OPTIONS]\n\nPrint an HTTPS site config to stdout; no system files are changed.\n\n", app, options.Server)
		flags.PrintDefaults()
	}
	if err := flags.Parse(args[1:]); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return err
	}
	if flags.NArg() != 0 {
		return errors.New("unexpected positional arguments; use proxy-config --help")
	}
	config, err := Render(options)
	if err != nil {
		return err
	}
	_, err = io.WriteString(out, config)
	return err
}

// Render validates every substituted value before generating any output.
func Render(options Options) (string, error) {
	path, err := templatePath(options.Server)
	if err != nil {
		return "", err
	}
	if !validDomain(options.Domain) {
		return "", errors.New("--domain must be a DNS hostname without a scheme, port, wildcard, or path")
	}
	if options.Upstream == "" {
		options.Upstream = defaultUpstream
	}
	if !validUpstream(options.Upstream) {
		return "", errors.New("--upstream must be localhost or a loopback IP with a port from 1 to 65535 (for example 127.0.0.1:8082)")
	}
	if options.Server == "caddy" && (options.Certificate != "" || options.Key != "") {
		return "", errors.New("Caddy manages TLS automatically; --tls-cert and --tls-key apply to nginx and Apache")
	}
	if (options.Certificate == "") != (options.Key == "") {
		return "", errors.New("provide both --tls-cert and --tls-key")
	}
	if options.Certificate == "" {
		options.Certificate = "/etc/letsencrypt/live/" + options.Domain + "/fullchain.pem"
		options.Key = "/etc/letsencrypt/live/" + options.Domain + "/privkey.pem"
	}
	if !validCertificatePath(options.Certificate) || !validCertificatePath(options.Key) {
		return "", errors.New("TLS paths must be absolute and use only letters, digits, spaces, /, ., _, and -")
	}
	data, err := examples.ReadFile(path)
	if err != nil {
		return "", err
	}
	config := strings.NewReplacer(
		"/etc/letsencrypt/live/"+exampleDomain+"/fullchain.pem", strconv.Quote(options.Certificate),
		"/etc/letsencrypt/live/"+exampleDomain+"/privkey.pem", strconv.Quote(options.Key),
		exampleDomain, options.Domain,
		defaultUpstream, options.Upstream,
	).Replace(string(data))
	prefix := strings.ToUpper(app)
	header := fmt.Sprintf("# Generated by %s proxy-config %s.\n# Set these in /etc/conf.d/%s (OpenRC) or /etc/%s/%s.env (systemd):\n# %s_ADDR=%s\n# %s_BASE_URL=https://%s\n# %s_SECURE_COOKIES=true\n# %s\n# Validate the complete proxy configuration before reloading.\n\n", app, options.Server, app, app, app, prefix, options.Upstream, prefix, options.Domain, prefix, proxyEnvironment)
	return header + config, nil
}

func templatePath(server string) (string, error) {
	switch server {
	case "caddy":
		return "caddy/Caddyfile", nil
	case "nginx", "apache":
		return server + "/" + app + ".conf", nil
	default:
		return "", fmt.Errorf("unsupported proxy %q; choose caddy, nginx, or apache", server)
	}
}

func validDomain(domain string) bool {
	if domain == "" || len(domain) > 253 {
		return false
	}
	for _, label := range strings.Split(domain, ".") {
		if label == "" || len(label) > 63 || label[0] == '-' || label[len(label)-1] == '-' {
			return false
		}
		for _, ch := range label {
			if !asciiAlphanumeric(ch) && ch != '-' {
				return false
			}
		}
	}
	return true
}

func validUpstream(upstream string) bool {
	host, port, err := net.SplitHostPort(upstream)
	if err != nil || strings.Trim(port, "0123456789") != "" {
		return false
	}
	number, err := strconv.ParseUint(port, 10, 16)
	if err != nil || number == 0 {
		return false
	}
	if host == "localhost" {
		return true
	}
	address, err := netip.ParseAddr(host)
	return err == nil && address.Zone() == "" && address.IsLoopback()
}

func validCertificatePath(path string) bool {
	if !filepath.IsAbs(path) || strings.HasSuffix(path, "/") {
		return false
	}
	for _, ch := range path {
		if !asciiAlphanumeric(ch) && !strings.ContainsRune("/._- ", ch) {
			return false
		}
	}
	return true
}

func asciiAlphanumeric(ch rune) bool {
	return ch >= 'a' && ch <= 'z' || ch >= 'A' && ch <= 'Z' || ch >= '0' && ch <= '9'
}
