ALTER TABLE boards ADD COLUMN restricted INTEGER NOT NULL DEFAULT 0 CHECK(restricted IN (0, 1));
ALTER TABLE boards ADD COLUMN revision INTEGER NOT NULL DEFAULT 0;
CREATE TABLE board_members (
	board_id INTEGER NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	access TEXT NOT NULL CHECK(access IN ('read', 'write')),
	PRIMARY KEY(board_id, user_id)
);
ALTER TABLE posts ADD COLUMN edited_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN revision INTEGER NOT NULL DEFAULT 0;
